version: 2.1
jobs:
  master-build:
    working_directory: ~/cafienne-engine
    machine:
      image: ubuntu-1604:202007-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: Updating Java and sbt versions
          command: |
            sudo apt-get update
            sudo apt install openjdk-11-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            java -version
            SBT_VERSION=$(awk -F"=" '/sbt.version/{print $NF}' project/build.properties)
            wget https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            sudo dpkg -i sbt-$SBT_VERSION.deb
            sbt sbtVersion
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Updating node version to 10.22.0
          command: |
            nvm install v10.22.0
            nvm alias default v10.22.0
            node -v
      - run:
          name: Compile code
          command: sbt compile
      - run:
          name: Unit tests
          command: sbt test
      - run:
          name: Clone CMMN-test framework
          command: |
            cd ..
            git clone https://$GIT_USER:$GIT_PASS@github.com/cafienne/cmmn-test-framework.git
      - run:
          name: Install dependencies
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm install
      - run:
          name: Docker login
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Pull DB and IDP docker images
          command: |
            docker pull cassandra:3.11
            docker pull postgres:12.1-alpine
            docker pull batav/circle-ci:postgres-event-data
            docker pull batav/circle-ci:sqlserver
            docker pull batav/circle-ci:sqlserver-event-data
            docker pull spectare/oidc-token-test-service:latest
      - run:
          name: Build cafienne docker image
          command: sbt docker:publishLocal

      # By the time of cassandra, sql-server, postgres testing, all the below containers will be up.
      - run:
          name: Start DB and IDP containers
          command: |
            docker-compose -f .circleci/docker-test-jdbc-master.yml up -d sql-server cafienne-event-db cafienne-query-db
            docker-compose -f .circleci/docker-test-cassandra.yml up -d cassandra postgres
            docker-compose -f .circleci/docker-test-inmemory.yml up -d cafienne-test-token-service

      # Starting docker environment for In-memory testing
      - run:
          name: Up the containers for In-memory testing
          command: |
            docker-compose -f .circleci/docker-test-inmemory.yml up -d cafienne
            sleep 10
            docker logs sql-server
      - run:
          name: Give permissions
          command: sudo chmod -R 777 ./
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
      - run:
          name: Test engine against framework
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm run dev
      - run:
          name: Stop the cafienne container
          command: docker rm -f cafienne

      # Starting docker environment for backwards compatibility Postgresql testing against latest engine
      - run:
          name: Up the containers for backwards compatibility Postgresql testing
          command: |
            sudo docker-compose -f .circleci/docker-test-jdbc-master.yml up -d cafienne-postgres
            sleep 10
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
      - run:
          name: Test engine against framework
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm run dev
      - run:
          name: Stop the containers
          command: docker rm -f cafienne cafienne-event-db cafienne-query-db

      # Starting docker environment for backwards compatibility Sqlserver testing against latest engine
      - run:
          name: Up the containers for backwards compatibility Sqlserver testing
          command: |
            sudo docker-compose -f .circleci/docker-test-jdbc-master.yml up -d cafienne-sqlserver
            sleep 10
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
      - run:
          name: Test engine against framework
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm run dev
      - run:
          name: Stop the containers
          command: docker rm -f cafienne sql-server

      # Starting docker environment for Cassandra testing
      - run:
          name: Up the containers for Cassandra testing
          command: |
            sudo docker-compose -f .circleci/docker-test-cassandra.yml up -d cafienne
            sleep 10
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
      - run:
          name: Test engine against framework
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm run dev
      - run:
          name: Stop the containers
          command: docker rm -f cafienne cassandra postgres

      # Starting plain Postgresql and Sqlserver DBs
      - run:
          name: Start DB and IDP containers
          command: docker-compose -f .circleci/docker-test-jdbc-release.yml up -d sql-server cafienne-event-db cafienne-query-db

      # Starting docker environment for Postgresql testing
      - run:
          name: Up the containers for Postgresql testing
          command: |
            sudo docker-compose -f .circleci/docker-test-jdbc-release.yml up -d cafienne-postgres
            sleep 10
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
      - run:
          name: Test engine against framework
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm run dev
      - run:
          name: Stop the containers
          command: docker rm -f cafienne cafienne-event-db cafienne-query-db

      # Starting docker environment for Sqlserver testing
      - run:
          name: Up the containers for Sqlserver testing
          command: |
            sudo docker-compose -f .circleci/docker-test-jdbc-release.yml up -d cafienne-sqlserver
            sleep 10
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
      - run:
          name: Test engine against framework
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm run dev
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
          when: on_fail
      - run:
          name: Stop the containers
          command: docker rm -f cafienne sql-server cafienne-test-token-service
      - run:
          name: Push cafienne image to docker hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
            then
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker push cafienne/engine:latest
            else
              echo "Not pushing image to docker hub"
            fi

  branch-build:
    working_directory: ~/cafienne-engine
    machine:
      image: ubuntu-1604:202007-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: Updating Java and sbt versions
          command: |
            sudo apt-get update
            sudo apt install openjdk-11-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            java -version
            SBT_VERSION=$(awk -F"=" '/sbt.version/{print $NF}' project/build.properties)
            wget https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            sudo dpkg -i sbt-$SBT_VERSION.deb
            sbt sbtVersion
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Updating node version to 10.22.0
          command: |
            nvm install v10.22.0
            nvm alias default v10.22.0
            node -v
      - run:
          name: Compile code
          command: sbt compile
      - run:
          name: Unit tests
          command: sbt test
      - run:
          name: Clone CMMN-test framework
          command: |
            cd ..
            git clone https://$GIT_USER:$GIT_PASS@github.com/cafienne/cmmn-test-framework.git
      - run:
          name: Install dependencies
          command: |
            cd ..
            cd ./cmmn-test-framework
            git checkout $CIRCLE_BRANCH || git checkout master
            npm install
      - run:
          name: Docker login
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Pull IDP docker image
          command: docker pull spectare/oidc-token-test-service:latest
      - run:
          name: Build cafienne docker image
          command: sbt docker:publishLocal

      # Starting docker environment for In-memory testing
      - run:
          name: Up the containers for In-memory testing
          command: |
            sudo docker-compose -f .circleci/docker-test-inmemory.yml up -d
            sleep 10
      - run:
          name: Give permissions
          command: sudo chmod -R 777 ./
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
      - run:
          name: Test engine against framework
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm run dev
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
          when: on_fail
      - run:
          name: Stop the containers
          command: |
            docker-compose -f .circleci/docker-test-inmemory.yml stop
            docker rm $(docker ps -a -q)

  release-build:
    working_directory: ~/cafienne-engine
    machine:
      image: ubuntu-1604:202007-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: Updating Java and sbt versions
          command: |
            sudo apt-get update
            sudo apt install openjdk-11-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            java -version
            SBT_VERSION=$(awk -F"=" '/sbt.version/{print $NF}' project/build.properties)
            wget https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            sudo dpkg -i sbt-$SBT_VERSION.deb
            sbt sbtVersion
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Updating node version to 10.22.0
          command: |
            nvm install v10.22.0
            nvm alias default v10.22.0
            node -v
      - run:
          name: Check for version TAG
          command: |
            echo `git describe --tags --exact-match` > ./version.txt
            cat ./version.txt
            TAG=$(cat ./version.txt)
      - run:
          name: Compile code
          command: sbt compile
      - run:
          name: Unit tests
          command: sbt test
      - run:
          name: Clone CMMN-test framework
          command: |
            cd ..
            git clone https://$GIT_USER:$GIT_PASS@github.com/cafienne/cmmn-test-framework.git
      - run:
          name: Install dependencies
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm install
      - run:
          name: Docker login
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Pull DB and IDP docker images
          command: |
            docker pull cassandra:3.11
            docker pull postgres:12.1-alpine
            docker pull batav/circle-ci:postgres-event-data
            docker pull batav/circle-ci:sqlserver
            docker pull batav/circle-ci:sqlserver-event-data
            docker pull spectare/oidc-token-test-service:latest
      - run:
          name: Build cafienne docker image
          command: sbt docker:publishLocal

      # By the time of cassandra, sql-server, postgres testing, all the below containers will be up.
      - run:
          name: Start DB and IDP containers
          command: |
            docker-compose -f .circleci/docker-test-jdbc-master.yml up -d sql-server cafienne-event-db cafienne-query-db
            docker-compose -f .circleci/docker-test-cassandra.yml up -d cassandra postgres
            docker-compose -f .circleci/docker-test-inmemory.yml up -d cafienne-test-token-service

      # Starting docker environment for In-memory testing
      - run:
          name: Up the containers for In-memory testing
          command: |
            docker-compose -f .circleci/docker-test-inmemory.yml up -d cafienne
            sleep 10
            docker logs sql-server
      - run:
          name: Give permissions
          command: sudo chmod -R 777 ./
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
      - run:
          name: Test engine against framework
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm run dev
      - run:
          name: Stop the cafienne container
          command: docker rm -f cafienne

      # Starting docker environment for backwards compatibility Postgresql testing against latest engine
      - run:
          name: Up the containers for backwards compatibility Postgresql testing
          command: |
            sudo docker-compose -f .circleci/docker-test-jdbc-master.yml up -d cafienne-postgres
            sleep 10
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
      - run:
          name: Test engine against framework
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm run dev
      - run:
          name: Stop the containers
          command: docker rm -f cafienne cafienne-event-db cafienne-query-db

      # Starting docker environment for backwards compatibility Sqlserver testing against latest engine
      - run:
          name: Up the containers for backwards compatibility Sqlserver testing
          command: |
            sudo docker-compose -f .circleci/docker-test-jdbc-master.yml up -d cafienne-sqlserver
            sleep 10
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
      - run:
          name: Test engine against framework
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm run dev
      - run:
          name: Stop the containers
          command: docker rm -f cafienne sql-server

      # Starting docker environment for Cassandra testing
      - run:
          name: Up the containers for Cassandra testing
          command: |
            sudo docker-compose -f .circleci/docker-test-cassandra.yml up -d cafienne
            sleep 10
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
      - run:
          name: Test engine against framework
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm run dev
      - run:
          name: Stop the containers
          command: docker rm -f cafienne cassandra postgres

      # Starting plain Postgresql and Sqlserver DBs
      - run:
          name: Start DB and IDP containers
          command: docker-compose -f .circleci/docker-test-jdbc-release.yml up -d sql-server cafienne-event-db cafienne-query-db

      # Starting docker environment for Postgresql testing
      - run:
          name: Up the containers for Postgresql testing
          command: |
            sudo docker-compose -f .circleci/docker-test-jdbc-release.yml up -d cafienne-postgres
            sleep 10
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
      - run:
          name: Test engine against framework
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm run dev
      - run:
          name: Stop the containers
          command: docker rm -f cafienne cafienne-event-db cafienne-query-db

      # Starting docker environment for Sqlserver testing
      - run:
          name: Up the containers for Sqlserver testing
          command: |
            sudo docker-compose -f .circleci/docker-test-jdbc-release.yml up -d cafienne-sqlserver
            sleep 10
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
      - run:
          name: Test engine against framework
          command: |
            cd ..
            cd ./cmmn-test-framework
            npm run dev
      - run:
          name: Docker logs of engine
          command: docker logs cafienne
          when: on_fail
      - run:
          name: Stop the containers
          command: docker rm -f cafienne sql-server cafienne-test-token-service
      - run:
          name: Push cafienne image to docker hub
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker tag cafienne/engine:latest cafienne/engine:$CIRCLE_TAG
            docker push cafienne/engine:$CIRCLE_TAG


workflows:
  version: 2
  ci:
    jobs:
      - master-build:
          filters:
            branches:
              only:
                - master
                - dependency-updates
      - branch-build:
          filters:
            branches:
              ignore:
                - master
                - dependency-updates
      - release-build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/