version: '3.1'
services:

  cassandra:
    image: cassandra:3.11
    labels:
      component: event-store
    network_mode: host
    expose:
      - 9042
    ports:
      - "9042:9042"
    container_name: cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "--execute", "show version;quit"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:12.1-alpine
    network_mode: host
    expose:
      - 5432
    ports:
      - "5432:5432"
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: cafienne-query

  cafienne-test-token-service:
    image: spectare/oidc-token-test-service:latest
    labels:
      component: idp-test-service-for-cafienne
    network_mode: host
    expose:
      - 2377
    ports:
      - "2377:2377"
    hostname: cafienne-test-token-service
    container_name: cafienne-test-token-service
    environment:
      BIND: 0.0.0.0
      PORT: 2377

  cafienne:
    image: cafienne/engine:latest
    labels:
      component: cafienne-engine
    network_mode: host
    expose:
      - 2027
    ports:
      - "2027:2027"
    hostname: cafienne
    container_name: cafienne
    environment:
      CS_HOST: ${CS_HOST:-127.0.0.1}
      PROJECTION_DB_URL: ${PROJECTION_DB_URL:-jdbc:postgresql://127.0.0.1:5432/cafienne-query?reWriteBatchedInserts=true}
    healthcheck:
      test: ["CMD", "wget", "-s", "http://localhost:2027/api-docs/swagger.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/circleci/cafienne-engine/.circleci/run/cafienne/journal:/opt/cafienne/journal
      - /home/circleci/cafienne-engine/.circleci/target/definitions:/opt/cafienne/definitions
      - /home/circleci/cafienne-engine/.circleci/target/documents:/opt/cafienne/documents
      - /home/circleci/cafienne-engine/.circleci/src/cassandra-conf:/opt/cafienne/conf
      - /home/circleci/cafienne-engine/.circleci/src/bootstrap:/opt/cafienne/bootstrap
    depends_on:
      - cassandra
      - postgres
      - cafienne-test-token-service